if {0} {
Write a Tcl program that:

Uses catch to execute expr {10 / 2}.
Stores the result.
Checks whether an error occurred.
Prints the result if successful.
Prints an error message if the operation fails.
}



if {[catch {expr {10/2}} result]} {
    puts "Error : $result"
} else {
    puts "Result : $result"
}



































if {0} {
| Command              | Purpose                              |
| -------------------- | ------------------------------------ |
| `catch`              | Catch errors generated by a command  |
| `error`              | Explicitly generate an error         |
| `try`                | Structured error handling            |
| `throw`              | Generate an error with an error code |
| `return -code error` | Return an error from a procedure     |


What catch Returns

catch returns:

0 → command succeeded
1 → command generated an error
}